version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: lpr-postgres
    restart: unless-stopped

    ports:
      - "5435:5432"

    environment:
      POSTGRES_DB: lpr_db
      POSTGRES_USER: lpr_user
      POSTGRES_PASSWORD: strongpassword

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lpr_user -d lpr_db"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - lpr-network   # just list the network name here

volumes:
  postgres_data:

networks:
  lpr-network:
    external: true   # define external network only at top level
