version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      BLUEPRINT_DB_HOST: ${BLUEPRINT_DB_HOST}       # e.g., lpr-postgres
      BLUEPRINT_DB_PORT: ${BLUEPRINT_DB_PORT}       # e.g., 5432
      BLUEPRINT_DB_DATABASE: ${BLUEPRINT_DB_DATABASE}
      BLUEPRINT_DB_USERNAME: ${BLUEPRINT_DB_USERNAME}
      BLUEPRINT_DB_PASSWORD: ${BLUEPRINT_DB_PASSWORD}
    networks:
      blueprint:
        external: true
        name: lpr-network      # <-- external network shared with Postgres / other services

volumes:
  postgres_data_bp:

networks:
  blueprint:
    external: true
    name: lpr-network
