version: "3.8"

services:
  plate-recognizer-1:
    image: platerecognizer/alpr
    container_name: plate-recognizer-1
    ports:
      - "8080:8080"
    environment:
      TOKEN: 2ee83fb34e74d1bd32772ac11129862e8f8161e1
      LICENSE_KEY: zfK79uRXbg
    volumes:
      - license1:/license
    restart: unless-stopped
    networks:
      - lpr-network

  plate-recognizer-2:
    image: platerecognizer/alpr
    container_name: plate-recognizer-2
    ports:
      - "8081:8080"   # âœ… different HOST port
    environment:
      TOKEN: 2ee83fb34e74d1bd32772ac11129862e8f8161e1
      LICENSE_KEY: FLAyQTqfzh
    volumes:
      - license2:/license
    restart: unless-stopped
    networks:
      - lpr-network

volumes:
  license1:
  license2:

networks:
  lpr-network:
    external: true
