version: "3.8"

services:
  plate-recognizer:
    image: platerecognizer/alpr
    container_name: plate-recognizer
    ports:
      - "8080:8080"
    environment:
      TOKEN: 2ee83fb34e74d1bd32772ac11129862e8f8161e1
      LICENSE_KEY: FLAyQTqfzh
    volumes:
      - license:/license
    restart: unless-stopped

volumes:
  license:
